name: Deploy to EC2 (Dev)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    environment: Dev  # <-- Use your configured environment name here

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 400 key.pem

      - name: SSH and Deploy App
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker rm -f todo-container || true
            cd ~/todo || git clone https://github.com/test982298/todo.git ~/todo && cd ~/todo
            git pull origin main
            docker build -t todo .
            docker run -d -p 80:80 --name todo-container todo
          EOF
