name: Deploy CICD React App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 400 key.pem

      - name: Deploy to EC2 and run Docker
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker container stop cicd-container || true
            docker container rm cicd-container || true
            cd ~/cicd || git clone https://github.com/<your-username>/<your-repo>.git ~/cicd && cd ~/cicd
            git pull origin main
            docker build -t cicd .
            docker run -d -p 80:80 --name cicd-container cicd
          EOF
